import type { Metadata } from "next";
import "@repo/ui/styles.css";
import "../../app/globals.css";
import { Header } from "../(home)/components/Header";
import { SessionProvider } from "next-auth/react";
import { Sidebar } from "./components/Sidebar";

export const metadata: Metadata = {
  title: "invite",
  description: "Generated by invite",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <main className="flex gap-3 h-screen mx-auto w-full max-w-screen-2xl p-1 bg-slate-100 overflow-hidden">
        <Sidebar /> 
        <div className=" p-1 w-full bg-white shadow-[0px_2px_3px_-1px_rgba(0,0,0,0.1),0px_1px_0px_0px_rgba(25,28,33,0.02),0px_0px_0px_1px_rgba(25,28,33,0.08)]">
          {children}
        </div>
      </main>
    </SessionProvider>
  );
}
