packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - bcrypt
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
