import type { Metadata } from "next";
import "@repo/ui/styles.css";
import "../../app/globals.css"
import { auth } from "@/auth";
import { Header } from "../(home)/components/Header";

export const metadata: Metadata = {
  title: "invite",
  description: "Generated by invite",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authData = await auth();
  return (
      <div className="bg-slate-100 text-black dark:bg-black dark:text-white">
        <Header authData={authData?.user} disableAnimation="disable"/>
        {children}
      </div>
    
  );
}